"""Add Tag and PhotoTag models

Revision ID: 0a57f3bd43de
Revises: abdd8b3b7828
Create Date: 2026-01-29 01:28:45.309146

"""
from alembic import op
from app.core.config import settings
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a57f3bd43de'
down_revision = 'abdd8b3b7828'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted manually ###
    # Inspection to make migration idempotent
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names(schema=settings.DB_SCHEMA)

    if 'tags' not in tables:
        op.create_table('tags',
        sa.Column('tag_id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('category', sa.String(length=50), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.PrimaryKeyConstraint('tag_id'),
        sa.UniqueConstraint('name'),
        schema=settings.DB_SCHEMA
        )
    
    if 'photo_tags' not in tables:
        op.create_table('photo_tags',
        sa.Column('photo_id', sa.UUID(), nullable=False),
        sa.Column('tag_id', sa.UUID(), nullable=False),
        sa.Column('confidence', sa.Float(), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['photo_id'], [f'{settings.DB_SCHEMA}.photos.photo_id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['tag_id'], [f'{settings.DB_SCHEMA}.tags.tag_id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('photo_id', 'tag_id'),
        schema=settings.DB_SCHEMA
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - adjusted manually ###
    op.drop_table('photo_tags', schema=settings.DB_SCHEMA)
    op.drop_table('tags', schema=settings.DB_SCHEMA)
    # ### end Alembic commands ###
    # ### end Alembic commands ###
