"""add_collaborators_and_link_views

Revision ID: 0ec071d65af6
Revises: 58b6b50a0398
Create Date: 2026-01-29 00:49:40.178611

"""
from alembic import op
from app.core.config import settings
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ec071d65af6'
down_revision = '58b6b50a0398'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('album_contributors',
    sa.Column('album_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], [f'{settings.DB_SCHEMA}.albums.album_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], [f'{settings.DB_SCHEMA}.users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('album_id', 'user_id'),
    schema=settings.DB_SCHEMA
    )
    op.create_table('share_link_views',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('share_link_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('ip_hash', sa.String(length=64), nullable=True),
    sa.Column('viewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['share_link_id'], [f'{settings.DB_SCHEMA}.share_links.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], [f'{settings.DB_SCHEMA}.users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema=settings.DB_SCHEMA
    )
    op.create_index(op.f('ix_photobomb_share_link_views_share_link_id'), 'share_link_views', ['share_link_id'], unique=False, schema=settings.DB_SCHEMA)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photobomb_share_link_views_share_link_id'), table_name='share_link_views', schema=settings.DB_SCHEMA)
    op.drop_table('share_link_views', schema=settings.DB_SCHEMA)
    op.drop_table('album_contributors', schema=settings.DB_SCHEMA)
    # ### end Alembic commands ###
