"""Add albums table and album_photos junction table

Revision ID: 3dac54efea17
Revises: 001
Create Date: 2025-12-12 02:19:19.246357

"""
from alembic import op
from app.core.config import settings
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3dac54efea17'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Only create albums and album_photos tables (users, photos, photo_files already exist)
    
    # Inspection to make migration idempotent
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names(schema=settings.DB_SCHEMA)

    if 'albums' not in tables:
        op.create_table('albums',
        sa.Column('album_id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('cover_photo_id', sa.UUID(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['cover_photo_id'], [f'{settings.DB_SCHEMA}.photos.photo_id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['user_id'], [f'{settings.DB_SCHEMA}.users.user_id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('album_id'),
        schema=settings.DB_SCHEMA
        )
        op.create_index(op.f('ix_photobomb_albums_user_id'), 'albums', ['user_id'], unique=False, schema=settings.DB_SCHEMA)
    
    if 'album_photos' not in tables:
        op.create_table('album_photos',
        sa.Column('album_id', sa.UUID(), nullable=False),
        sa.Column('photo_id', sa.UUID(), nullable=False),
        sa.Column('added_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['album_id'], [f'{settings.DB_SCHEMA}.albums.album_id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['photo_id'], [f'{settings.DB_SCHEMA}.photos.photo_id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('album_id', 'photo_id'),
        schema=settings.DB_SCHEMA
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('album_photos', schema=settings.DB_SCHEMA)
    op.drop_index(op.f('ix_photobomb_albums_user_id'), table_name='albums', schema=settings.DB_SCHEMA)
    op.drop_table('albums', schema=settings.DB_SCHEMA)
    # ### end Alembic commands ###
