"""add admin_job indexes

Revision ID: 80af9f6500bd
Revises: f345dc32710b
Create Date: 2026-02-13 21:53:05.753742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80af9f6500bd'
down_revision = 'f345dc32710b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
