"""add admin_job indexes

Revision ID: 80af9f6500bd
Revises: f345dc32710b
Create Date: 2026-02-13 21:53:05.753742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80af9f6500bd'
down_revision = 'f345dc32710b'
branch_labels = None
depends_on = None


from app.core.config import settings

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_admin_jobs_status', 'admin_jobs', ['status'], unique=False, schema=settings.DB_SCHEMA)
    op.create_index('idx_admin_jobs_created', 'admin_jobs', ['created_at'], unique=False, schema=settings.DB_SCHEMA)
    op.create_index('idx_admin_jobs_user_id', 'admin_jobs', ['user_id'], unique=False, schema=settings.DB_SCHEMA)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_admin_jobs_user_id', table_name='admin_jobs', schema=settings.DB_SCHEMA)
    op.drop_index('idx_admin_jobs_created', table_name='admin_jobs', schema=settings.DB_SCHEMA)
    op.drop_index('idx_admin_jobs_status', table_name='admin_jobs', schema=settings.DB_SCHEMA)
    # ### end Alembic commands ###
