"""add_hashtag_and_tag_category_indexes

Revision ID: 833cad635c49
Revises: 12535d1cf2ad
Create Date: 2026-01-30 02:38:25.888518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '833cad635c49'
down_revision = '12535d1cf2ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_tags_category', 'tags', ['category'], unique=False, schema=settings.DB_SCHEMA)
    op.create_index('idx_photo_tags_tag_id', 'photo_tags', ['tag_id'], unique=False, schema=settings.DB_SCHEMA)
    op.create_index('idx_photo_tags_tag_confidence', 'photo_tags', ['tag_id', 'confidence'], unique=False, schema=settings.DB_SCHEMA)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_photo_tags_tag_confidence', table_name='photo_tags', schema=settings.DB_SCHEMA)
    op.drop_index('idx_photo_tags_tag_id', table_name='photo_tags', schema=settings.DB_SCHEMA)
    op.drop_index('idx_tags_category', table_name='tags', schema=settings.DB_SCHEMA)
    # ### end Alembic commands ###
