"""Add Person and Face models

Revision ID: abdd8b3b7828
Revises: 0ec071d65af6
Create Date: 2026-01-29 01:13:26.486238

"""
from alembic import op
from app.core.config import settings
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision = 'abdd8b3b7828'
down_revision = '0ec071d65af6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - adjusted manually ###
    # Inspection to make migration idempotent
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names(schema=settings.DB_SCHEMA)

    if 'people' not in tables:
        op.create_table('people',
        sa.Column('person_id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=True),
        sa.Column('cover_face_id', sa.UUID(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['cover_face_id'], [f'{settings.DB_SCHEMA}.faces.face_id'], ondelete='SET NULL', use_alter=True),
        sa.ForeignKeyConstraint(['user_id'], [f'{settings.DB_SCHEMA}.users.user_id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('person_id'),
        schema=settings.DB_SCHEMA
        )
    
    if 'faces' not in tables:
        op.create_table('faces',
        sa.Column('face_id', sa.UUID(), nullable=False),
        sa.Column('photo_id', sa.UUID(), nullable=False),
        sa.Column('person_id', sa.UUID(), nullable=True),
        sa.Column('encoding', pgvector.sqlalchemy.vector.VECTOR(dim=128), nullable=True),
        sa.Column('location_top', sa.Integer(), nullable=False),
        sa.Column('location_right', sa.Integer(), nullable=False),
        sa.Column('location_bottom', sa.Integer(), nullable=False),
        sa.Column('location_left', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['person_id'], [f'{settings.DB_SCHEMA}.people.person_id'], ondelete='SET NULL'),
        sa.ForeignKeyConstraint(['photo_id'], [f'{settings.DB_SCHEMA}.photos.photo_id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('face_id'),
        schema=settings.DB_SCHEMA
        )
        op.create_index('idx_faces_person', 'faces', ['person_id'], unique=False, schema=settings.DB_SCHEMA)
        op.create_index('idx_faces_photo', 'faces', ['photo_id'], unique=False, schema=settings.DB_SCHEMA)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - adjusted manually ###
    op.drop_index('idx_faces_photo', table_name='faces', schema=settings.DB_SCHEMA)
    op.drop_index('idx_faces_person', table_name='faces', schema=settings.DB_SCHEMA)
    op.drop_table('faces', schema=settings.DB_SCHEMA)
    op.drop_table('people', schema=settings.DB_SCHEMA)
    # ### end Alembic commands ###
