"""optimize_indexes

Revision ID: e368bd6ca6b0
Revises: 3dac54efea17
Create Date: 2025-12-21 09:08:18.438108

"""
from alembic import op
from app.core.config import settings
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision = 'e368bd6ca6b0'
down_revision = '3dac54efea17'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Get database connection
    bind = op.get_bind()
    inspector = Inspector.from_engine(bind)
    
    # Check if indexes exist before creating to avoid errors
    # Note: We assume tables exist because the previous autogen tried to recreate them
    
    # 1. idx_photos_user_deleted
    # Manual check since inspector.get_indexes() might need schema handling
    try:
        op.create_index('idx_photos_user_deleted', 'photos', ['user_id', 'deleted_at'], unique=False, schema=settings.DB_SCHEMA, postgresql_where='deleted_at IS NOT NULL')
    except Exception:
        pass # Index likely exists or table missing
        
    # 2. idx_albums_user_updated
    try:
        op.create_index('idx_albums_user_updated', 'albums', ['user_id', 'updated_at'], unique=False, schema=settings.DB_SCHEMA)
    except Exception:
        pass
        
    # 3. ix_photobomb_album_photos_photo_id (FK index)
    try:
        op.create_index(op.f('ix_photobomb_album_photos_photo_id'), 'album_photos', ['photo_id'], unique=False, schema=settings.DB_SCHEMA)
    except Exception:
        pass


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photobomb_album_photos_photo_id'), table_name='album_photos', schema=settings.DB_SCHEMA)
    op.drop_index('idx_albums_user_updated', table_name='albums', schema=settings.DB_SCHEMA)
    op.drop_index('idx_photos_user_deleted', table_name='photos', schema=settings.DB_SCHEMA, postgresql_where='deleted_at IS NOT NULL')
    # ### end Alembic commands ###

