"""Add is_admin to users

Revision ID: f345dc32710b
Revises: 833cad635c49
Create Date: 2026-02-04 23:53:34.426959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f345dc32710b'
down_revision = '833cad635c49'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_photobomb_album_photos_photo_id', table_name='album_photos', schema='photobomb_dev')
    op.create_index(op.f('ix_photobomb_dev_album_photos_photo_id'), 'album_photos', ['photo_id'], unique=False, schema='photobomb_dev')
    op.drop_index('ix_photobomb_albums_user_id', table_name='albums', schema='photobomb_dev')
    op.create_index(op.f('ix_photobomb_dev_albums_user_id'), 'albums', ['user_id'], unique=False, schema='photobomb_dev')
    op.drop_index('ix_faces_person_photo', table_name='faces', schema='photobomb_dev')
    op.create_foreign_key(None, 'people', 'faces', ['cover_face_id'], ['face_id'], source_schema='photobomb_dev', referent_schema='photobomb_dev', ondelete='SET NULL', use_alter=True)
    op.drop_index('ix_photobomb_share_link_views_share_link_id', table_name='share_link_views', schema='photobomb_dev')
    op.create_index(op.f('ix_photobomb_dev_share_link_views_share_link_id'), 'share_link_views', ['share_link_id'], unique=False, schema='photobomb_dev')
    op.drop_index('ix_photobomb_share_links_album_id', table_name='share_links', schema='photobomb_dev')
    op.drop_index('ix_photobomb_share_links_token', table_name='share_links', schema='photobomb_dev')
    op.create_index(op.f('ix_photobomb_dev_share_links_album_id'), 'share_links', ['album_id'], unique=False, schema='photobomb_dev')
    op.create_index(op.f('ix_photobomb_dev_share_links_token'), 'share_links', ['token'], unique=True, schema='photobomb_dev')
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True), schema='photobomb_dev')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin', schema='photobomb_dev')
    op.drop_index(op.f('ix_photobomb_dev_share_links_token'), table_name='share_links', schema='photobomb_dev')
    op.drop_index(op.f('ix_photobomb_dev_share_links_album_id'), table_name='share_links', schema='photobomb_dev')
    op.create_index('ix_photobomb_share_links_token', 'share_links', ['token'], unique=False, schema='photobomb_dev')
    op.create_index('ix_photobomb_share_links_album_id', 'share_links', ['album_id'], unique=False, schema='photobomb_dev')
    op.drop_index(op.f('ix_photobomb_dev_share_link_views_share_link_id'), table_name='share_link_views', schema='photobomb_dev')
    op.create_index('ix_photobomb_share_link_views_share_link_id', 'share_link_views', ['share_link_id'], unique=False, schema='photobomb_dev')
    op.drop_constraint(None, 'people', schema='photobomb_dev', type_='foreignkey')
    op.create_index('ix_faces_person_photo', 'faces', ['person_id', 'photo_id'], unique=False, schema='photobomb_dev')
    op.drop_index(op.f('ix_photobomb_dev_albums_user_id'), table_name='albums', schema='photobomb_dev')
    op.create_index('ix_photobomb_albums_user_id', 'albums', ['user_id'], unique=False, schema='photobomb_dev')
    op.drop_index(op.f('ix_photobomb_dev_album_photos_photo_id'), table_name='album_photos', schema='photobomb_dev')
    op.create_index('ix_photobomb_album_photos_photo_id', 'album_photos', ['photo_id'], unique=False, schema='photobomb_dev')
    # ### end Alembic commands ###
