"""Add ShareLink model

Revision ID: fc167775b497
Revises: e368bd6ca6b0
Create Date: 2026-01-11 23:06:12.829716

"""
from alembic import op
from app.core.config import settings
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc167775b497'
down_revision = 'e368bd6ca6b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Inspection to make migration idempotent
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names(schema=settings.DB_SCHEMA)

    if 'share_links' not in tables:
        op.create_table('share_links',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('album_id', sa.UUID(), nullable=False),
        sa.Column('token', sa.String(length=64), nullable=False),
        sa.Column('is_public', sa.Boolean(), nullable=True),
        sa.Column('expires_at', sa.DateTime(), nullable=True),
        sa.Column('allowed_emails', sa.JSON(), nullable=True),
        sa.Column('views', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['album_id'], [f'{settings.DB_SCHEMA}.albums.album_id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        schema=settings.DB_SCHEMA
        )
        op.create_index(op.f('ix_photobomb_share_links_album_id'), 'share_links', ['album_id'], unique=False, schema=settings.DB_SCHEMA)
        op.create_index(op.f('ix_photobomb_share_links_token'), 'share_links', ['token'], unique=True, schema=settings.DB_SCHEMA)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photobomb_share_links_token'), table_name='share_links', schema=settings.DB_SCHEMA)
    op.drop_index(op.f('ix_photobomb_share_links_album_id'), table_name='share_links', schema=settings.DB_SCHEMA)
    op.drop_table('share_links', schema=settings.DB_SCHEMA)
    # ### end Alembic commands ###
    # ### end Alembic commands ###
